trigger:
 branches:
   include:
   - az_artifact
 paths:
  exclude:
    - README.md

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
   versionSpec : '3.*'
  displayName: 'Choix de la version Python'

- script: |
   pip install --upgrade pip
   pip install build twine setuptools wheel keyring artifacts-keyring
  displayName: 'Installation des outils Python'

- script: |
   python setup.py sdist bdist_wheel
  displayName: 'Build Package'

- task: TwineAuthenticate@1
  inputs:
   artifactFeed: 'Proj-CI-CD-Template/py_app'
  displayName: 'Connection au feed'

- script: |
    python -m twine upload -r py_app --config-file $(PYPIRC_PATH) dist/* --verbose
  displayName: 'Upload sur le feed'